apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubewatch
  namespace: default
  labels:
    app: kubewatch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubewatch
  template:
    metadata:
      namespace: default
      labels:
        app: kubewatch
    spec:
      serviceAccountName: kubewatch
      containers:
      - image: tpageforfunzies/kubewatcharmhf:v2
        imagePullPolicy: Always
        name: kubewatch
        volumeMounts:
        - name: config-volume
          mountPath: /root
      imagePullSecrets:
        - name: myregistrykey
      restartPolicy: Always
      volumes:
      - name: config-volume
        configMap:
          name: kubewatch
